name: Format

on:
  push:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang-format
      - run: find -iname "*.cpp" -or -iname "*.hpp" -exec clang-format -style=file -i {} \;
      - name: Commit
        continue-on-error: true
        run: |
          git config --global user.name 'CI'
          git config --global user.email ''
          git add .
          git diff-index --quiet HEAD || git commit -am "[RUN] clang-format"
          git push